function [MLS, Positivebasis]=MINlat(B)
%MINlat (B) provides the minimal lattice-subspace
%generated by a given finite collection of positive,
%linearly independent vectors of Rn
%B denotes the matrix whose columns are the given vectors
[N,M]=size(B);
for i = 1:N,
if norm(B(i,:),1)~=0,
Test(i,:)=1/norm(B (i,:),1)*B(i,:);
end
end
Matrix = Test;
[ii,jj]=find(Matrix);
Matrix1 = Matrix(unique(ii),:);
BB = unique(Matrix1,'rows');
M1 = rank(bsxfun(@minus,BB,BB(1,:)));
if M1 < M,
Utrans = bsxfun(@minus,BB,BB(1,:));
Rot = orth(Utrans');
Uproj = Utrans*Rot;
Tri = convhulln(Uproj);
VIndex = unique(Tri(:));
P = BB(VIndex,:)';
Q = length(VIndex);
else
VIndex = unique(convhulln(BB));
P = BB(VIndex,:)';
Q = length(VIndex);
end
Test = zeros(N,M);
for i = 1:N,
Test (i,:)=1/norm(B(i,:),1)*B(i,:);
end
Matrix = Test;
BBB = Matrix';
R = Q-M;
Sol = zeros(Q,R);
for i = 1:N,
Sol(:,i)=lsqnonneg(P,BBB(:,i));
end
Solutions = Sol;
Norms = sum(B,2)';
Test1 = zeros(R,N);
for i = 1:R,
Index1 = M+i;
D = Solutions(Index1,:).*Norms*eye(N);
Test1(i,:)=D;
end
Minlatsub=[B';Test1];
MLS = Minlatsub;
Positivebasis = SUBlatSUB(MLS');
end